### ISSUE TITLE
[Bug] HA Core 2026.9: vacuum platform fails to set up — VacuumEntityFeature.BATTERY was removed

### ISSUE THREAD

**Issue by keyusertraining-ops** [ifMike/homeyHASS#33]
## Summary

On Home Assistant Core **2026.9.0**, the `vacuum` platform fails to set up entirely.
`VacuumEntityFeature.BATTERY` was removed from the core enum, and `vacuum.py` line 87
still references it, so `HomeyVacuum.__init__` raises before any entity is created.

This is not a degradation of the battery reading — **every vacuum entity disappears**.

## Traceback

```
2026-09-05 20:13:36.430 ERROR (MainThread) [homeassistant.components.vacuum]
Error while setting up homey_hass platform for vacuum: type object 'VacuumEntityFeature' has no attribute 'BATTERY'
  File "/config/custom_components/homey_hass/vacuum.py", line 54, in async_setup_entry
    entities.append(HomeyVacuum(coordinator, device_id, device, api, zones, homey_id, multi_homey))
  File "/config/custom_components/homey_hass/vacuum.py", line 87, in __init__
    supported_features = VacuumEntityFeature.STATE | VacuumEntityFeature.BATTERY
AttributeError: type object 'VacuumEntityFeature' has no attribute 'BATTERY'
```

## Environment

- Home Assistant Core 2026.9.0 (HA OS 18.2, Python 3.14)
- homeyHASS 2.1.0, installed via HACS (matches `main` at the time of writing)
- Two vacuum devices bridged from Homey (a vacuum and a mop)

## Cause

The 2026.9 release notes list this under backward-incompatible changes, in the Vacuum
section:

> The deprecated `battery_level` property has been removed from the base vacuum entity.
> All core vacuum integrations were already migrated in Home Assistant 2026.8. If a custom
> integration still sets this property, it no longer reports a battery level; add a
> separate battery sensor instead.

The wording only describes the property, but the feature flag went with it, and that flag
is what breaks setup. Home Assistant had been warning about the property since 2026.8:

```
WARNING [homeassistant.helpers.frame] Detected that custom integration 'homey_hass' is setting
the battery_level which has been deprecated. Integration homey_hass should implement a sensor
instead with a correct device class and link it to the same device.
This will stop working in Home Assistant 2026.8
```

This is the same class of breakage as #8 and #11 (`CoverEntityFeature.SET_COVER_POSITION`
and `CoverEntityFeature.POSITION`), so the fix pattern should look familiar.

## Fix

Dropping the flag is enough to restore the platform:

```diff
--- a/custom_components/homey_hass/vacuum.py
+++ b/custom_components/homey_hass/vacuum.py
@@ -84,7 +84,9 @@
         capabilities = device.get("capabilitiesObj", {})
         
         # Determine supported features based on available capabilities
-        supported_features = VacuumEntityFeature.STATE | VacuumEntityFeature.BATTERY
+        # BATTERY retire de VacuumEntityFeature en HA Core 2026.9 : le niveau de
+        # batterie passe desormais par un capteur dedie, plus par l'entite vacuum.
+        supported_features = VacuumEntityFeature.STATE
         
         if "clean_full" in capabilities and capabilities.get("clean_full", {}).get("setable"):
             supported_features |= VacuumEntityFeature.TURN_ON | VacuumEntityFeature.START
```

Verified on the affected instance: the platform sets up again, both vacuum entities are
back, and no error remains in the log.

I deliberately kept the change minimal and did **not** touch the `battery_level` property
at line 144. It is now inert rather than harmful — HA simply ignores it. Following the
release note properly would mean exposing the Homey `measure_battery` capability as its own
battery sensor entity linked to the same device, which is a larger change and yours to
design.

## Secondary, not urgent

`homey_hass` also triggers this on every startup:

```
WARNING [homeassistant.helpers.frame] Detected that custom integration 'homey_hass' calls
`device_registry.async_get_device`, which is deprecated
```

Not breaking anything today, but it is the same kind of debt and will eventually be
enforced the way the vacuum flag just was.

Happy to open a PR for the one-line fix if that is easier for you.

**Comment by ifMike** [comment]
Fixed in **v2.1.1**: `VacuumEntityFeature.BATTERY` is only used when still present on older Home Assistant; on 2026.9+ the vacuum platform no longer crashes. Battery remains available via the existing `measure_battery` sensor.

Release: https://github.com/ifMike/homeyHASS/releases/tag/v2.1.1
